// Offline browser integration test using synthetic in-memory SpiGes only.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.CHIQI_PLAYWRIGHT_PATH || 'playwright');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const errors = [], network = [];
const xml = `<?xml version="1.0"?><Unternehmen ent_id="SYNTHETIC" version="1.5" xmlns="http://www.bfs.admin.ch/xmlns/gvs/spiges-data"><Standort burnr="SYNTHETIC">${Array.from({ length: 20 }, (_, i) => `<Fall fall_id="SYNTHETIC-CASE-${i}"><Administratives geschlecht="2" alter="60" eintrittsdatum="2026010108" austrittsdatum="2026010312" austrittsentscheid="1" eintritt_aufenthalt="1" eintrittsart="1"/><Diagnose diagnose_id="1" diagnose_kode="C509"/><Behandlung behandlung_id="1" behandlung_chop="${i < 15 ? '85.21' : '85.41'}"/></Fall>`).join('')}</Standort></Unternehmen>`;
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, offline: true });
  const page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (/^https?:/.test(r.url())) network.push(r.url()); });
  await page.addInitScript(() => { window.print = () => {}; });
  await page.goto(new URL('./chiqi/index.html', import.meta.url).href);
  await page.locator('#fileInput').setInputFiles({ name: 'synthetic-breast.xml', mimeType: 'text/xml', buffer: Buffer.from(xml) });
  await page.waitForFunction(() => document.querySelector('#status').textContent.includes('abgeschlossen'));
  const tr = page.locator('#indTable tr').filter({ hasText: 'G5_03' });
  assert.deepEqual(await tr.locator('td').allTextContents(), ['G5_03Anteil brusterhaltende Resektionen bei Brustkrebs', '20', '15', '75.0%', '76.0%', '–', '0', '0']);
  await page.locator('[data-indicator="G5_03"]').click();
  assert.match(await page.locator('#wbIndicator').innerText(), /brusterhaltend/);
  assert.doesNotMatch(await page.locator('#wbIndicator').innerText(), /Todesfälle|verstorben|SMR/);
  assert.equal(await page.locator('[data-path="plan.targetMetric"]').inputValue(), 'Rate');
  assert.equal(await page.locator('[data-path="check.E"]').count(), 0);
  await page.locator('[data-path="check.n"]').fill('40');
  await page.locator('[data-path="check.n"]').dispatchEvent('change');
  await page.locator('[data-path="check.O"]').fill('32');
  await page.locator('[data-path="check.O"]').dispatchEvent('change');
  assert.match(await page.locator('.impact-box').innerText(), /Anteil 80.0%/);
  await page.locator('[data-path="owner"]').fill('Synthetic reviewer');
  await page.locator('[data-path="owner"]').dispatchEvent('change');
  const stored = await page.evaluate(() => localStorage.getItem('chiqiKompass.qmProjects.v1'));
  assert.ok(stored.includes('Synthetic reviewer'));
  assert.doesNotMatch(stored, /SYNTHETIC-CASE-|C509|8521/);
  await page.locator('#btnPdf').click();
  assert.match(await page.locator('#report').innerText(), /G5_03: Anteil 75.0% \(15\/20 Resektionsfälle\)/);
  assert.doesNotMatch(await page.locator('#report').innerText(), /G5_03[^.]*liegender Mortalität/);
  await page.evaluate(() => document.body.classList.remove('rep-mode'));
  fs.mkdirSync(new URL('../tmp/breast-qa/', import.meta.url), { recursive: true });
  await page.locator('#workbenchCard').screenshot({ path: fileURLToPath(new URL('../tmp/breast-qa/workbench.png', import.meta.url)) });
  await page.locator('#btnCockpit').click();
  await page.waitForURL(/cockpit\.html$/);
  await page.waitForFunction(() => document.querySelector('#own-inst').options.length > 0);
  assert.match(await page.locator('#own-transfer-title').innerText(), /4 Indikatoren/);
  const institution = await page.locator('#own-inst option').evaluateAll(options => options.find(o => o.textContent.startsWith('Klinik Hirslanden AG'))?.value);
  assert.ok(institution);
  await page.selectOption('#own-inst', institution);
  await page.locator('#own-confirm').click();
  await page.selectOption('#own-ind', 'G.5.3.P');
  const table = await page.locator('#own-history-table').innerText();
  assert.match(table, /75\.0%/);
  assert.match(table, /568/);
  assert.match(table, /2333|2[’'\s]333/);
  assert.doesNotMatch(table, /SMR|Mortalität/);
  assert.match(await page.locator('#own-status').innerText(), /richtungsneutral/);
  await page.locator('#own-history-card').screenshot({ path: fileURLToPath(new URL('../tmp/breast-qa/comparison.png', import.meta.url)) });
  // Switching back must still show the original mortality semantics.
  await page.selectOption('#own-ind', 'A.1.1.M');
  assert.match(await page.locator('#own-history-table').innerText(), /SMR/);
  // Exercise the same path through the actual landing-page iframe shell.
  await page.goto(new URL('./index.html#chiqi', import.meta.url).href);
  const frame = page.frameLocator('#frame');
  await frame.locator('#fileInput').setInputFiles({ name: 'synthetic-breast.xml', mimeType: 'text/xml', buffer: Buffer.from(xml) });
  await frame.locator('#status').filter({ hasText: 'abgeschlossen' }).waitFor();
  await frame.locator('#btnCockpit').click();
  await frame.locator('#own-transfer-title').filter({ hasText: '4 Indikatoren' }).waitFor();
  assert.deepEqual(errors, []);
  assert.deepEqual(network, [], 'no network requests, including chart dependencies');
  console.log('PASS offline browser: XML → 15/20 breast share → local PDCA → report → aggregate transfer → verified BAG denominators; mortality switch unchanged; no network or JavaScript errors');
} finally { await browser.close(); }
